from __future__ import annotations

from datetime import datetime, date

from ..models import User
from ..data_layer.report_repository import report_repo


class ReportService:
    """
    Service for generating financial and operational reports.

    This service acts as the Business Intelligence (BI) layer, aggregating raw
    transactional data into meaningful insights. It supports high-level decision-making
    by providing summaries of revenue, expenses, and accounts receivable (debt).
    """

    def doctor_revenue(
            self,
            current_user: User,
            *,
            date_from: datetime | date | None,
            date_to: datetime | date | None,
            doctor_id: int | None,
    ):
        """
        Aggregates revenue generated by doctors.

        Calculates the total value of payments associated with each doctor's plans
        within a specific date range. Useful for performance tracking and payroll estimation.
        """
        clinic_id = current_user.clinic_id
        if not clinic_id:
            return None, "user has no clinic assigned"

        items = report_repo.doctor_revenue(
            clinic_id=clinic_id,
            date_from=date_from,
            date_to=date_to,
            doctor_id=doctor_id,
        )
        return items, None

    def category_expenses(
            self,
            current_user: User,
            *,
            date_from: datetime | date | None,
            date_to: datetime | date | None,
    ):
        """
        Summarizes clinic expenses by category.

        Groups manual cash transactions (e.g., 'Office Supplies', 'Maintenance')
        to provide a breakdown of operational costs over a given period.
        """
        clinic_id = current_user.clinic_id
        if not clinic_id:
            return None, "user has no clinic assigned"

        items = report_repo.category_expenses(
            clinic_id=clinic_id,
            date_from=date_from,
            date_to=date_to,
        )
        return items, None

    def cashbox_summary(
            self,
            current_user: User,
            *,
            date_from: datetime | date | None,
            date_to: datetime | date | None,
    ):
        """
        Provides a snapshot of cashbox activity.

        Aggregates Total In (Revenue) and Total Out (Expenses/Payouts) per cashbox.
        Used to monitor physical cash flow and liquidity.
        """
        clinic_id = current_user.clinic_id
        if not clinic_id:
            return None, "user has no clinic assigned"

        items = report_repo.cashbox_summary(
            clinic_id=clinic_id,
            date_from=date_from,
            date_to=date_to,
        )
        return items, None

    def patient_financial_summary(
            self,
            current_user: User,
            patient_id: int,
    ):
        """
        Retrieves a 360-degree financial view for a specific patient.

        Combines data from Installment Plans and Payments to calculate:
        - Total Planned Amount (Lifetime Value)
        - Total Paid Amount
        - Total Outstanding Debt
        """
        clinic_id = current_user.clinic_id
        if not clinic_id:
            return None, "user has no clinic assigned"

        data = report_repo.patient_financial_summary(
            clinic_id=clinic_id,
            patient_id=patient_id,
        )
        if not data:
            return None, "patient not found or no data"
        return data, None

    def top_debtors(
            self,
            current_user: User,
            *,
            limit: int = 20,
    ):
        """
        Identifies patients with the highest outstanding debt.

        This report is critical for Accounts Receivable (AR) management, allowing
        the clinic to prioritize collection efforts on high-value outstanding plans.
        """
        clinic_id = current_user.clinic_id
        if not clinic_id:
            return None, "user has no clinic assigned"

        items = report_repo.top_debtors(
            clinic_id=clinic_id,
            limit=limit,
        )
        return items, None


report_service = ReportService()
