"""Add tip and tip_payout models

Revision ID: 0710ebf3f19e
Revises: 2cc7ced34a46
Create Date: 2025-11-30 21:17:57.196126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0710ebf3f19e'
down_revision = '2cc7ced34a46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tip_payout',
    sa.Column('payout_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], name=op.f('fk_tip_payout_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], name=op.f('fk_tip_payout_created_by_user')),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.user_id'], name=op.f('fk_tip_payout_doctor_id_user')),
    sa.PrimaryKeyConstraint('payout_id', name=op.f('pk_tip_payout'))
    )
    op.create_table('tip',
    sa.Column('tip_id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinic.clinic_id'], name=op.f('fk_tip_clinic_id_clinic')),
    sa.ForeignKeyConstraint(['created_by'], ['user.user_id'], name=op.f('fk_tip_created_by_user')),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.user_id'], name=op.f('fk_tip_doctor_id_user')),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.patient_id'], name=op.f('fk_tip_patient_id_patient')),
    sa.ForeignKeyConstraint(['plan_id'], ['installment_plan.plan_id'], name=op.f('fk_tip_plan_id_installment_plan')),
    sa.PrimaryKeyConstraint('tip_id', name=op.f('pk_tip'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tip')
    op.drop_table('tip_payout')
    # ### end Alembic commands ###
