"""Update PIN schema

Revision ID: 09ef4a8fd590
Revises: b87e57596fd9
Create Date: 2025-12-13 19:25:14.943536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ef4a8fd590'
down_revision = 'b87e57596fd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.alter_column('session_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('daily_close', schema=None) as batch_op:
        batch_op.alter_column('session_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('session_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tip_payout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_tip_payout_session_user_id_user'), 'user', ['session_user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tip_payout', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tip_payout_session_user_id_user'), type_='foreignkey')
        batch_op.drop_column('session_user_id')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.alter_column('session_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('daily_close', schema=None) as batch_op:
        batch_op.alter_column('session_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.alter_column('session_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
