"""add timezone to clinic

Revision ID: 12acdf997168
Revises: 491ecfd970d4
Create Date: 2026-03-17 15:26:31.573804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12acdf997168'
down_revision = '491ecfd970d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=60), nullable=False, server_default='UTC'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
