"""add tip links to cash_transaction and make cashbox.active non-null

Revision ID: 2822df1ea88e
Revises: 0710ebf3f19e
Create Date: 2025-12-01 17:16:28.932293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2822df1ea88e'
down_revision = '0710ebf3f19e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tip_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tip_payout_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cash_transaction_tip_payout_id_tip_payout'), 'tip_payout', ['tip_payout_id'], ['payout_id'])
        batch_op.create_foreign_key(batch_op.f('fk_cash_transaction_tip_id_tip'), 'tip', ['tip_id'], ['tip_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_transaction_tip_id_tip'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_cash_transaction_tip_payout_id_tip_payout'), type_='foreignkey')
        batch_op.drop_column('tip_payout_id')
        batch_op.drop_column('tip_id')

    # ### end Alembic commands ###
