"""Updated installment_plan and installment models

Revision ID: 2cc7ced34a46
Revises: cfaa7fb8786d
Create Date: 2025-11-29 12:16:28.298346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc7ced34a46'
down_revision = 'cfaa7fb8786d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False))

    with op.batch_alter_table('installment_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_payment_method', sa.Enum('CASH', 'CARD', 'TRANSFER', 'OTHER', name='paymentmethod'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('installment_plan', schema=None) as batch_op:
        batch_op.drop_column('default_payment_method')

    with op.batch_alter_table('installment', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
