"""add token_version to user for revocation

Revision ID: 491ecfd970d4
Revises: 5e96d32d0658
Create Date: 2025-12-23 17:19:48.416588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491ecfd970d4'
down_revision = '5e96d32d0658'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        # Added server_default='1' to fix NotNullViolation on existing rows
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('token_version')

    # ### end Alembic commands ###