"""add is_default bool to cashbox

Revision ID: 4a455f028a2c
Revises: ea216d1d3e00
Create Date: 2025-12-22 19:30:10.973282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a455f028a2c'
down_revision = 'ea216d1d3e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###
