"""Add clinic auth settings + user PIN, JWT Config

Revision ID: 54f50ef68b36
Revises: 060e2a98ae33
Create Date: 2025-11-24 19:01:48.984706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54f50ef68b36'
down_revision = '060e2a98ae33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('use_shared_terminal_mode', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('require_pin_for_actions', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('require_pin_for_signoff', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pin_hash')

    with op.batch_alter_table('clinic', schema=None) as batch_op:
        batch_op.drop_column('require_pin_for_signoff')
        batch_op.drop_column('require_pin_for_actions')
        batch_op.drop_column('use_shared_terminal_mode')

    # ### end Alembic commands ###
