"""add constraint one default cashbox per clinic

Revision ID: 5e96d32d0658
Revises: 4a455f028a2c
Create Date: 2025-12-22 19:35:46.232289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e96d32d0658'
down_revision = '4a455f028a2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.create_index('ix_unique_default_per_clinic', ['clinic_id'], unique=True, sqlite_where=sa.text('is_default = true'), postgresql_where=sa.text('is_default = true'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.drop_index('ix_unique_default_per_clinic', sqlite_where=sa.text('is_default = true'), postgresql_where=sa.text('is_default = true'))

    # ### end Alembic commands ###
