"""Add constraints to audit_log Model, update User and Tip Models

Revision ID: 6580f3a51074
Revises: ec81193714ce
Create Date: 2025-12-12 19:39:12.249903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6580f3a51074'
down_revision = 'ec81193714ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_clinic_action', ['clinic_id', 'action'], unique=False)
        batch_op.create_index('ix_audit_log_clinic_created_at', ['clinic_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_log_clinic_entity', ['clinic_id', 'entity_name', 'entity_id'], unique=False)
        batch_op.create_unique_constraint('uq_audit_log_clinic_curr_hash', ['clinic_id', 'curr_hash'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_clinic_email'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_user_clinic_email'), ['clinic_id', 'email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_constraint('uq_audit_log_clinic_curr_hash', type_='unique')
        batch_op.drop_index('ix_audit_log_clinic_entity')
        batch_op.drop_index('ix_audit_log_clinic_created_at')
        batch_op.drop_index('ix_audit_log_clinic_action')

    # ### end Alembic commands ###
