"""Add dob and middle_name to patient

Revision ID: a709fd010d06
Revises: 09ef4a8fd590
Create Date: 2025-12-15 17:48:19.075123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a709fd010d06'
down_revision = '09ef4a8fd590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('birth_date')
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
