"""Initial schema with dual user tracking

Revision ID: b87e57596fd9
Revises: 6580f3a51074
Create Date: 2025-12-13 11:28:55.165540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b87e57596fd9'
down_revision = '6580f3a51074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_cash_transaction_session_user_id_user'), 'user', ['session_user_id'], ['user_id'])

    with op.batch_alter_table('daily_close', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_daily_close_session_user_id_user'), 'user', ['session_user_id'], ['user_id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payment_session_user_id_user'), 'user', ['session_user_id'], ['user_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_session_user_id_user'), type_='foreignkey')
        batch_op.drop_column('session_user_id')

    with op.batch_alter_table('daily_close', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_daily_close_session_user_id_user'), type_='foreignkey')
        batch_op.drop_column('session_user_id')

    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_cash_transaction_session_user_id_user'), type_='foreignkey')
        batch_op.drop_column('session_user_id')

    # ### end Alembic commands ###
