"""Update fincacials  models to support status, user can approve financials

Revision ID: cf6910eae635
Revises: 8c5631f19009
Create Date: 2025-12-19 16:54:46.934115

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf6910eae635'
down_revision = '8c5631f19009'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # 1. Convert CashTransaction Status from Enum to String
    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        batch_op.alter_column('status',
                              existing_type=postgresql.ENUM('PENDING', 'APPROVED', name='transactionstatus'),
                              type_=sa.String(length=50),
                              existing_nullable=False,
                              # Just in case there is data, this ensures proper casting
                              postgresql_using='status::text')

    # 2. Add status to DailyClose (Default: APPROVED)
    with op.batch_alter_table('daily_close', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='APPROVED'))

    # 3. Add status to Payment (Default: PAID)
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='PAID'))

    # 4. Add status to TipPayout (Default: CONFIRMED)
    with op.batch_alter_table('tip_payout', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='CONFIRMED'))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tip_payout_approved_by_user'), 'user', ['approved_by'], ['user_id'])

    # 5. Add can_approve_financials to User (Default: false)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('can_approve_financials', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('can_approve_financials')

    with op.batch_alter_table('tip_payout', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_tip_payout_approved_by_user'), type_='foreignkey')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('status')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('daily_close', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('cash_transaction', schema=None) as batch_op:
        # Revert String back to Enum
        # Note: 'transactionstatus' enum type might need explicit creation if it was dropped,
        # but usually batch_alter handles the type conversion if PostgreSQL supports casting string -> enum.
        # Ideally we'd ensure the type exists, but this is standard auto-gen logic.
        batch_op.alter_column('status',
                              existing_type=sa.String(length=50),
                              type_=postgresql.ENUM('PENDING', 'APPROVED', name='transactionstatus'),
                              existing_nullable=False,
                              postgresql_using='status::transactionstatus')

    # ### end Alembic commands ###
