"""Made patients email composite unique with clinic

Revision ID: cfaa7fb8786d
Revises: 54f50ef68b36
Create Date: 2025-11-28 18:11:22.783181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfaa7fb8786d'
down_revision = '54f50ef68b36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_patient_email'), type_='unique')
        batch_op.create_unique_constraint('uq_patient_clinic_email', ['clinic_id', 'email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint('uq_patient_clinic_email', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_patient_email'), ['email'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
