"""Add cashbox fk to payment

Revision ID: ea216d1d3e00
Revises: cf6910eae635
Create Date: 2025-12-19 18:52:55.699282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea216d1d3e00'
down_revision = 'cf6910eae635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_cashbox_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_payment_target_cashbox_id_cashbox'), 'cashbox', ['target_cashbox_id'], ['cashbox_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_payment_target_cashbox_id_cashbox'), type_='foreignkey')
        batch_op.drop_column('target_cashbox_id')

    # ### end Alembic commands ###
