"""add current_amount to casbox

Revision ID: ec81193714ce
Revises: 2822df1ea88e
Create Date: 2025-12-01 18:34:23.485492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec81193714ce'
down_revision = '2822df1ea88e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_amount', sa.Numeric(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cashbox', schema=None) as batch_op:
        batch_op.drop_column('current_amount')

    # ### end Alembic commands ###
